defaults:
  - experiment: default
  - override hydra/sweeper: optuna
  - _self_

data:
  train_path: data/raw/train.csv
  test_path: data/raw/test.csv
  submission_path: data/processed/submission.csv

mlflow:
  tracking_uri: mlruns
  experiment_name: kaggle_06_predicting_f1_pit_stops

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
    direction: maximize
    n_trials: 10
    params:
      experiment.params.learning_rate: interval(0.001, 0.1)
      experiment.params.num_leaves: choice(31, 63, 127, 255)
